import "./src/components/dom.js";
import "./src/components/addcontact.js";
import "./src/components/render.js";
import "./src/components/error.js";
import "./src/components/search.js";
import "./src/components/edit.js";
import "./src/components/delete.js";
import "./src/components/listener.js";
import "./src/components/field.js"
import "./src/components/local.js"
import "./src/components/state.js"